# Generated by Django 4.2.28 on 2026-02-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='content',
        ),
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(default='', help_text='Detailed professional bio'),
        ),
        migrations.AddField(
            model_name='about',
            name='happy_clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='projects_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='System Architecture', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='level_label',
            field=models.CharField(default='Expert', max_length=50),
        ),
        migrations.AlterField(
            model_name='about',
            name='ats_summary',
            field=models.TextField(default='', help_text='Plain text for ATS'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
